- hosts: metals
  gather_facts: no
  become: yes

  tasks:
  - name: create /var/demi/cron
    file:
      name: /var/demi/cron
      state: directory

  - name: load dynv6.net token
    set_fact:
      dynv6_token: "{{ lookup('file', 'keys/dynv6_token') }}"

  - name: copy metal_cron_book.yaml
    template:
      dest: /var/demi/cron/metal_cron_book.yaml
      src: metal_cron_book.yaml.j2
      mode: "0600"  # stores decrypted dynv6.net token

  - name: install cron job
    cron:
      name: "metal ansible tasks"
      cron_file: "metal_ansible_tasks"
      minute: "*"
      user: root
      job: "ansible-playbook /var/demi/cron/metal_cron_book.yaml"

  - name: add MAILTO to cron
    cron:
      cron_file: "metal_ansible_tasks"
      user: root
      name: MAILTO
      env: yes
      job: ""
      insertbefore: "metal ansible tasks"

