- hosts: all
  gather_facts: yes
  become: true

- hosts: demis
  gather_facts: no
  become: true

  handlers:
  - name: reload dns
    service:
      name: bind9
      state: reloaded
  
  tasks:
  - name: install dns
    package: 
      name: bind9
      state: present
      
  - name: copy named config
    copy:
      content: |
        zone "demi.ro" {
            type master;
            file "/etc/bind/db.demi.ro";
        };
      dest: /etc/bind/named.conf.local
    notify: reload dns
      
  - name: get public IPv4
    ipify_facts:
    run_once: yes

  - name: copy zone config
    template:
      dest: /etc/bind/db.demi.ro
      src: db.demi.ro
    notify: reload dns

  - name: create challenge files
    command:
      cmd: "touch /etc/bind/cert_txt.{{ item }}.include"
      creates: "/etc/bind/cert_txt.{{ item }}.include"
    loop: "{{ groups.demis }}"

  - meta: flush_handlers
