- hosts: kubes
  gather_facts: no
  become: yes

  tasks:
  - name: symlink glusterfs certificates
    file:
      dest: /etc/ssl/{{ item.0 }}
      src: /var/demi/ssl/{{ item.1 }}
      state: link
    loop:
      - [ glusterfs.pem, ssl.lan.demi.crt ]
      - [ glusterfs.crt, ssl.lan.demi.pem ]
      - [ glusterfs.ca, ssl.metal.root_ca_bundle.crt ]

  - name: create persistent glusterfs directory
    file:
      path: /mnt/persistent/glusterd
      state: directory
      mode: "0750"

  - name: set up persistent glusterfs directory
    file:
      dest: /var/lib/glusterd
      src: /mnt/persistent/glusterd
      state: link

  - name: install glusterfs
    package:
      name: glusterfs-server
      state: present
    
  - name: enable and start glusterd service
    service:
      name: glusterd
      enabled: yes
      state: started

  - name: add gluster peer
    gluster_peer:
      nodes:
        - kube1
        - kube2
      state: present

  - name: create gluster-bricks directory
    file:
      path: /mnt/persistent/gluster-bricks
      state: directory
      mode: "0750"

  - name: create gluster volume directories
    file:
      path: /mnt/persistent/gluster-bricks/{{item}}
      state: directory
    loop:
      - default-volume
      - grafana-volume
      - conduit-volume
      - conduit-dev-volume
      - synapse-dev-volume

  - name: add gluster volumes for Kubernetes
    gluster_volume:
      name: "{{item}}"
      bricks: /mnt/persistent/gluster-bricks/{{item}}
      cluster:
        - kube1
        - kube2
      state: present
    run_once: true
    loop:
      - default-volume
      - grafana-volume
      - conduit-volume
      - conduit-dev-volume
      - synapse-dev-volume

