- hosts: demis:kubes
  gather_facts: no

  tasks:
  - name: Add to loadbalancer
    uri:
      url: "http://openwrt-9-demi.lan/cgi-bin/loadbalancer?add={{ guest_ip }}"
      return_content: yes
    register: lb_result
    failed_when: "'Firewall reloaded successfully' not in lb_result.content"
    delegate_to: "{{ my_metal }}"
