- hosts: demis
  gather_facts: no

  tasks:
  - name: Remove from loadbalancer
    uri:
      url: "http://openwrt-9-demi/cgi-bin/loadbalancer?remove={{ demi_ip }}"
      return_content: yes
    register: lb_result
    failed_when: "'Firewall reloaded successfully' not in lb_result.content"
    delegate_to: "{{ my_metal }}"
