- hosts: demis
  gather_facts: no
  become: true

  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded
  
  tasks:
  - name: install nginx
    package: 
      name: nginx
      state: present
      
  - name: remove default nginx config
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: reload nginx
      
  - name: copy server config
    copy:
      src: site.80.conf
      dest: /etc/nginx/sites-available/site.80.conf
    notify: reload nginx
      
  - name: enable server config
    file:
      path: /etc/nginx/sites-enabled/site.80.conf
      src: /etc/nginx/sites-available/site.80.conf
      state: link
    notify: reload nginx
      
  - name: copy www files
    copy:
      src: "www/{{item}}"
      dest: "/var/www/html/{{item}}"
    loop:
      - favicon.ico
      - grumpy-demi.png
      - not-authorized.html
      - robots.txt
    tags: www
    notify: reload nginx
      
  - name: copy www templated files
    template:
      src: "www/{{item}}.j2"
      dest: "/var/www/html/{{item}}"
    loop:
      - index.html
    tags: www
    notify: reload nginx
      
  - name: copy server config
    copy:
      src: site.443.conf
      dest: /etc/nginx/sites-available/site.443.conf
    notify: reload nginx
    tags: site
      
  - name: enable server config
    file:
      path: /etc/nginx/sites-enabled/site.443.conf
      src: /etc/nginx/sites-available/site.443.conf
      state: link
    notify: reload nginx
      
  - meta: flush_handlers
