- hosts: all
  gather_facts: no
  become: true
  
  tasks:
  - name: create users
    user:
      name: "{{ item }}"
      shell: /bin/bash
      password: '*'
      generate_ssh_key: yes
      groups: sudo
      append: yes
    loop: "{{ demi_users.split(',') }}"
    tags: users

  - name: set sudoers
    copy:
      content: |
        %sudo   ALL=(ALL:ALL) NOPASSWD: ALL
      dest: /etc/sudoers.d/sudo_nopwd
      
  - name: set authorized_key
    authorized_key:
      user: char
      key: "{{ lookup('file', 'ssh_keys/' + item) }}"
    loop:
      - key.char@metal1.pub
      - key.char@localhost.pub
      
  - name: set authorized_key
    authorized_key:
      user: andrei
      key: "{{ lookup('file', 'ssh_keys/' + item) }}"
    loop:
      - key.andrei@metal1.pub
      - key.andrei@ANDREI-W10.pub
      - key.andrei@DESKTOP-02LV2TV.pub
      
  - name: set authorized_key
    authorized_key:
      user: lemon
      key: "{{ lookup('file', 'ssh_keys/' + item) }}"
    loop:
      - key.lemon@metal1.pub
      - key.lemon@whatever.pub
      
  - name: set authorized_key
    authorized_key:
      user: costel
      key: "{{ lookup('file', 'ssh_keys/' + item) }}"
    loop:
      - key.costel@edv.pub

  - name: set authorized_key
    authorized_key:
      user: ansible
      key: "{{ lookup('file', 'ssh_keys/' + item) }}"
    loop:
      - key.ansible@metal1.pub
      - key.andrei@metal1.pub
      - key.andrei@ANDREI-W10.pub
      - key.andrei@DESKTOP-02LV2TV.pub
      - key.lemon@metal1.pub
      - key.lemon@whatever.pub
      - key.char@metal1.pub
      - key.char@localhost.pub
      - key.costel@edv.pub
