- hosts: demis:kubes
  become: yes
  gather_facts: no

  tasks:
  - name: vagrant down
    command:
      cmd: "vagrant destroy -f {{ inventory_hostname }}"
      chdir: /var/demi/vagrant
    delegate_to: "{{ my_metal }}"
