- hosts: demis:kubes
  become: yes
  gather_facts: no

  tasks:
  - name: vagrant down
    command:
      cmd: "vagrant destroy -f {{ inventory_hostname }}"
      chdir: /var/demi/vagrant
    delegate_to: "{{ my_metal }}"

  - name: vagrant box update
    command:
      cmd: "vagrant box update {{ inventory_hostname }}"
      chdir: /var/demi/vagrant
    delegate_to: "{{ my_metal }}"

  # TODO: Changed when:
  # kube1: Box 'generic/debian11' (v3.6.0) is running the latest version.
  # ..not in output
