#!/usr/bin/lua

query_string = os.getenv("QUERY_STRING")

function return_400(text)
    print("Status: 401 Bad request")
    print()
    print("Invalid request: " .. text)
end

function return_200(text)
    print("Status: 200 OK")
    print()
    print(text)
end

targets = {
    ["192.168.16.21"] = "lb-targets",
    ["192.168.16.22"] = "lb-targets",
    ["192.168.16.31"] = "lbkube-targets",
    ["192.168.16.32"] = "lbkube-targets",
}

for action, target in string.gfind(query_string, "(%a+)=([%d\.]+)") do
    if not targets[target] then
        return_400("Target unknown.")
        return
    end

    lbdir = targets[target]

    if action == "add" then
        os.execute("touch /etc/" .. lbdir .. "/" .. target)
        action_made = "added"
    elseif action == "remove" then
        os.execute("rm /etc/" .. lbdir .. "/" .. target)
        action_made = "removed"
    else
        return_400("Action '" .. action .. "' not valid, must be one of 'add' or 'remove'")
        return
    end

    success = os.execute("sh /etc/firewall.user")
    reloaded = success and "successfully" or "unsuccessfully"
    return_200("Target " .. target .. " " .. action_made .. ". Firewall reloaded " .. reloaded .. ".")
    return
end

